MOVIES = [{'title': 'Ghilli',
  'year': 2004,
  'clues': ['Starring Vijay, a kabaddi player named Velu.',
            'The story revolves around a girl who escapes from a powerful man.',
            'Dharani directed the movie.']},
 {'title': 'Mankatha',
  'year': 2011,
  'clues': ['Starring Ajith Kumar, Vinayak Mahadevan.',
            'The story revolves around a group planning a cricket betting money heist.',
            'Venkat Prabhu directed the movie.']},
 {'title': 'Vikram',
  'year': 2022,
  'clues': ['Starring Kamal Haasan, a retired black-ops agent.',
            'The story involves a drug syndicate and a secret team.',
            'Lokesh Kanagaraj directed the movie.']},
 {'title': 'Master',
  'year': 2021,
  'clues': ['Starring Vijay, an alcoholic professor who teaches at a juvenile facility.',
            'The story involves a powerful criminal controlling young inmates.',
            'Lokesh Kanagaraj directed the movie.']},
 {'title': 'Kaithi',
  'year': 2019,
  'clues': ['Starring Karthi, Dilli, a recently released prisoner.',
            'The story takes place mainly over one night involving a police operation.',
            'Lokesh Kanagaraj directed the movie.']},
 {'title': 'Leo',
  'year': 2023,
  'clues': ['Starring Vijay, Parthiban, a café owner in Kashmir.',
            'The story connects him to a violent past and a drug family.',
            'Lokesh Kanagaraj directed the movie.']},
 {'title': 'Thuppakki',
  'year': 2012,
  'clues': ['Starring Vijay, an army officer who returns to Mumbai.',
            'He discovers a sleeper-cell network and tries to stop attacks.',
            'A. R. Murugadoss directed the movie.']},
 {'title': 'Kaththi',
  'year': 2014,
  'clues': ['Starring Vijay, dual roles as Kathiresan and Jeevanandham.',
            'The story focuses on farmers fighting for their land and water.',
            'A. R. Murugadoss directed the movie.']},
 {'title': '96',
  'year': 2018,
  'clues': ['Starring Vijay Sethupathi and Trisha, former schoolmates.',
            'The story follows their reunion at a school get-together.',
            'C. Prem Kumar directed the movie.']},
 {'title': 'Pizza',
  'year': 2012,
  'clues': ['Starring Vijay Sethupathi, a pizza delivery boy.',
            'A delivery to a mysterious house turns into a night of horror.',
            'Karthik Subbaraj directed the movie.']},
 {'title': 'Soodhu Kavvum',
  'year': 2013,
  'clues': ['Starring Vijay Sethupathi, Das, a small-time kidnapper.',
            'The story follows an unusual kidnapping gang and their chaotic plans.',
            'Nalan Kumarasamy directed the movie.']},
 {'title': 'Doctor',
  'year': 2021,
  'clues': ['Starring Sivakarthikeyan, a calm doctor named Varun.',
            'The story involves a team trying to rescue kidnapped children.',
            'Nelson Dilipkumar directed the movie.']},
 {'title': 'Don',
  'year': 2022,
  'clues': ['Starring Sivakarthikeyan, a college student named Sivakumar.',
            'The story mixes college life, friendship and a strict father.',
            'Cibi Chakaravarthi directed the movie.']},
 {'title': 'Jailer',
  'year': 2023,
  'clues': ['Starring Rajinikanth, retired jailer Muthuvel Pandian.',
            'The story involves his family and a dangerous criminal network.',
            'Nelson directed the movie.']},
 {'title': 'Enthiran',
  'year': 2010,
  'clues': ['Starring Rajinikanth, scientist Vaseegaran and a humanoid robot.',
            'The story explores a robot gaining emotions and turning dangerous.',
            'S. Shankar directed the movie.']},
 {'title': 'Anniyan',
  'year': 2005,
  'clues': ['Starring Vikram, Ambi, who has multiple personalities.',
            'A mysterious vigilante begins punishing people for social wrongs.',
            'S. Shankar directed the movie.']},
 {'title': 'Ayan',
  'year': 2009,
  'clues': ['Starring Suriya, Deva, a smuggler working in an international network.',
            'The story involves diamonds, drugs and a dangerous rival.',
            'K. V. Anand directed the movie.']},
 {'title': 'Singam',
  'year': 2010,
  'clues': ['Starring Suriya, police officer Durai Singam.',
            'He faces a powerful criminal while working in a coastal town.',
            'Hari directed the movie.']},
 {'title': 'Soorarai Pottru',
  'year': 2020,
  'clues': ['Starring Suriya, Maara, an ambitious young man.',
            'He dreams of making air travel affordable for ordinary people.',
            'Sudha Kongara directed the movie.']},
 {'title': 'Vaaranam Aayiram',
  'year': 2008,
  'clues': ['Starring Suriya, dual roles as a father and son.',
            'The story follows a son remembering his father through major life events.',
            'Gautham Vasudev Menon directed the movie.']},
 {'title': 'Vada Chennai',
  'year': 2018,
  'clues': ['Starring Dhanush, Anbu, a young carrom player from North Chennai.',
            'The story follows gangs, politics and rivalries across several years.',
            'Vetrimaaran directed the movie.']},
 {'title': 'Asuran',
  'year': 2019,
  'clues': ['Starring Dhanush, a farmer named Sivasami.',
            'The story follows a family facing caste violence and land conflict.',
            'Vetrimaaran directed the movie.']},
 {'title': 'Maari',
  'year': 2015,
  'clues': ['Starring Dhanush, Maari, a local rowdy with a distinctive style.',
            'The story mixes comedy, rivalry and a clash with a police officer.',
            'Balaji Mohan directed the movie.']},
 {'title': 'Thiruchitrambalam',
  'year': 2022,
  'clues': ['Starring Dhanush, Thiru, a young food delivery worker.',
            'The story follows friendship, family relationships and love.',
            'Mithran Jawahar directed the movie.']},
 {'title': 'Ratsasan',
  'year': 2018,
  'clues': ['Starring Vishnu Vishal, a police officer investigating murders.',
            'The case involves a mysterious serial killer targeting schoolgirls.',
            'R. Murali directed the movie.']},
 {'title': 'Theeran Adhigaaram Ondru',
  'year': 2017,
  'clues': ['Starring Karthi, police officer Theeran Thirumaran.',
            'The story is inspired by a police investigation into a notorious gang.',
            'H. Vinoth directed the movie.']},
 {'title': 'Pariyerum Perumal',
  'year': 2018,
  'clues': ['Starring Kathir, a law student named Pariyan.',
            'The story explores caste discrimination and social inequality.',
            'Mari Selvaraj directed the movie.']},
 {'title': 'Jai Bhim',
  'year': 2021,
  'clues': ['Starring Suriya, lawyer K. Chandru.',
            'The story follows a legal fight for justice for an oppressed tribal woman.',
            'T. J. Gnanavel directed the movie.']},
 {'title': 'Mandela',
  'year': 2021,
  'clues': ['Starring Yogi Babu, a barber known as Mandela.',
            'His single vote becomes crucial during a village election.',
            'Madonne Ashwin directed the movie.']},
 {'title': 'Good Night',
  'year': 2023,
  'clues': ['Starring K. Manikandan, a young IT employee named Mohan.',
            'His loud snoring creates problems in his newly married life.',
            'Vinayak Chandrasekaran directed the movie.']},
 {'title': 'Parking',
  'year': 2023,
  'clues': ['Starring Harish Kalyan and M. S. Bhaskar, neighbours who clash over a parking space.',
            'A small parking dispute gradually becomes a serious rivalry.',
            'Ramkumar Balakrishnan directed the movie.']},
 {'title': 'Gemini',
  'year': 2002,
  'clues': ['Starring Vikram, the lead.', 'The story follows a local rowdy.', 'Saran directed the movie.']},
 {'title': 'Thamizhan',
  'year': 2002,
  'clues': ['Starring Vijay, the lead.',
            'Priyanka Chopra makes her Tamil debut.',
            'The story involves corruption and justice.']},
 {'title': 'Thulluvadho Ilamai',
  'year': 2002,
  'clues': ['Starring Dhanush, the lead.',
            'The story follows school students.',
            'Kasthuri Raja directed the movie.']},
 {'title': 'Panchatanthiram',
  'year': 2002,
  'clues': ['Starring Kamal Haasan, the lead.',
            'The story is a comedy about five friends.',
            'K. S. Ravikumar directed the movie.']},
 {'title': 'Roja Koottam',
  'year': 2002,
  'clues': ['Starring Srikanth, the lead.', 'It is a romantic drama.', 'Sasi directed the movie.']},
 {'title': 'Run',
  'year': 2002,
  'clues': ['Starring Madhavan, the lead.',
            'Meera Jasmine is the female lead.',
            'N. Lingusamy directed the movie.']},
 {'title': 'Kadhal Azhivathillai',
  'year': 2002,
  'clues': ['Starring Silambarasan, the lead.',
            'It is a romantic drama.',
            'T. Rajendar produced the movie.']},
 {'title': 'Whistle',
  'year': 2003,
  'clues': ['Starring Vikramadithya, the lead.',
            'The story has a supernatural element.',
            'J. D. Jerry directed the movie.']},
 {'title': 'Kaaka Kaaka',
  'year': 2003,
  'clues': ['Starring Suriya, an encounter specialist.',
            'Jyothika is the female lead.',
            'Gautham Vasudev Menon directed the movie.']},
 {'title': 'Pithamagan',
  'year': 2003,
  'clues': ['Starring Vikram, a cemetery worker.', 'Suriya plays a conman.', 'Bala directed the movie.']},
 {'title': 'Boys',
  'year': 2003,
  'clues': ['Siddharth and Genelia are among the leads.',
            'The story follows a group of young friends.',
            'Shankar directed the movie.']},
 {'title': 'Parthiban Kanavu',
  'year': 2003,
  'clues': ['Starring Srikanth, the lead.', 'Sneha plays two roles.', 'Karikalan directed the movie.']},
 {'title': 'Anbe Sivam',
  'year': 2003,
  'clues': ['Starring Kamal Haasan and Madhavan.',
            'The story follows two strangers on a journey.',
            'Sundar C. directed the movie.']},
 {'title': 'Lesa Lesa',
  'year': 2003,
  'clues': ['Starring Shaam, the lead.', 'Trisha is the female lead.', 'Priyadarshan directed the movie.']},
 {'title': 'Iyarkai',
  'year': 2003,
  'clues': ['Starring Shaam, the lead.',
            'The story is set around a port town.',
            'S. P. Jananathan directed the movie.']},
 {'title': 'Thirumalai',
  'year': 2003,
  'clues': ['Starring Vijay, a mechanic.', 'Jyothika is the female lead.', 'Ramana directed the movie.']},
 {'title': 'M. Kumaran S/O Mahalakshmi',
  'year': 2004,
  'clues': ['Starring Jayam Ravi, a boxer.', 'Nadhiya plays his mother.', 'M. Raja directed the movie.']},
 {'title': 'Autograph',
  'year': 2004,
  'clues': ['Starring Cheran, the lead.',
            'The story revisits three stages of love.',
            'Cheran directed the movie.']},
 {'title': '7G Rainbow Colony',
  'year': 2004,
  'clues': ['Starring Ravi Krishna, the lead.',
            'The story is a coming-of-age romance.',
            'Selvaraghavan directed the movie.']},
 {'title': 'Kaadhal',
  'year': 2004,
  'clues': ['Starring Bharath, the lead.',
            'The story follows a mechanic and a young woman.',
            'Balaji Sakthivel directed the movie.']},
 {'title': 'Arul',
  'year': 2004,
  'clues': ['Starring Vikram, the lead.', 'Jyothika is the female lead.', 'Hari directed the movie.']},
 {'title': 'Aaytha Ezhuthu',
  'year': 2004,
  'clues': ['Starring Suriya, Madhavan and Siddharth.',
            'The story follows three interconnected lives.',
            'Mani Ratnam directed the movie.']},
 {'title': 'Manmadhan',
  'year': 2004,
  'clues': ['Starring Silambarasan, dual roles.',
            'The film is a romantic thriller.',
            'A. J. Murugan directed the movie.']},
 {'title': 'Vasool Raja MBBS',
  'year': 2004,
  'clues': ['Starring Kamal Haasan, a conman.',
            'The story is set in a medical college.',
            'Saran directed the movie.']},
 {'title': 'New',
  'year': 2004,
  'clues': ['Starring S. J. Suryah, the lead.',
            'The story involves a magical transformation.',
            'S. J. Suryah directed the movie.']},
 {'title': 'Ullam Ketkumae',
  'year': 2005,
  'clues': ['Shaam and Arya are among the leads.',
            'The story follows college friends.',
            'Jeeva directed the movie.']},
 {'title': 'Raam',
  'year': 2005,
  'clues': ['Starring Jiiva, the lead.', 'The story is a psychological drama.', 'Ameer directed the movie.']},
 {'title': 'Sandakozhi',
  'year': 2005,
  'clues': ['Starring Vishal, the lead.',
            'Rajkiran plays an important role.',
            'N. Lingusamy directed the movie.']},
 {'title': 'Ghajini',
  'year': 2005,
  'clues': ['Starring Suriya, Sanjay Ramasamy.',
            'The story involves short-term memory loss.',
            'A. R. Murugadoss directed the movie.']},
 {'title': 'Thirupaachi',
  'year': 2005,
  'clues': ['Starring Vijay, a blacksmith.',
            'The story involves fighting rowdies in Chennai.',
            'Perarasu directed the movie.']},
 {'title': 'Sivakasi',
  'year': 2005,
  'clues': ['Starring Vijay, a printer.',
            'The story involves a family conflict.',
            'Perarasu directed the movie.']},
 {'title': 'Kanda Naal Mudhal',
  'year': 2005,
  'clues': ['Starring Prasanna, the lead.',
            'Karthik Kumar is also prominent.',
            'V. Priya directed the movie.']},
 {'title': 'Pudhupettai',
  'year': 2006,
  'clues': ['Starring Dhanush, Kokki Kumar.',
            "The story follows a man's rise in the underworld.",
            'Selvaraghavan directed the movie.']},
 {'title': 'Vettaiyaadu Vilaiyaadu',
  'year': 2006,
  'clues': ['Starring Kamal Haasan, a police officer.',
            'The story follows a serial killer investigation.',
            'Gautham Vasudev Menon directed the movie.']},
 {'title': 'Pattiyal',
  'year': 2006,
  'clues': ['Starring Arya and Bharath, assassins.',
            'The story follows two contract killers.',
            'Vishnuvardhan directed the movie.']},
 {'title': 'Parijatham',
  'year': 2006,
  'clues': ['Starring Prithviraj, the lead.', 'It is a romantic drama.', 'K. Bhagyaraj directed the movie.']},
 {'title': 'Thiruvilaiyaadal Aarambam',
  'year': 2006,
  'clues': ['Starring Dhanush, a young man.',
            'Prakash Raj plays the antagonist.',
            'Bhoopathy Pandian directed the movie.']},
 {'title': 'Chennai 600028',
  'year': 2007,
  'clues': ['The story follows a group of cricket-playing friends.',
            'The sport is street cricket.',
            'Venkat Prabhu directed the movie.']},
 {'title': 'Polladhavan',
  'year': 2007,
  'clues': ['Starring Dhanush, a motorcycle enthusiast.',
            'The story revolves around a stolen bike.',
            'Vetrimaaran directed the movie.']},
 {'title': 'Paruthiveeran',
  'year': 2007,
  'clues': ['Starring Karthi, the lead.', 'Priyamani plays Muththazhagu.', 'Ameer directed the movie.']},
 {'title': 'Sivaji',
  'year': 2007,
  'clues': ['Starring Rajinikanth, a software engineer.',
            'Shriya Saran is the female lead.',
            'Shankar directed the movie.']},
 {'title': 'Billa',
  'year': 2007,
  'clues': ['Starring Ajith Kumar, a gangster and a police officer.',
            'Nayanthara is the female lead.',
            'Vishnuvardhan directed the movie.']},
 {'title': 'Vel',
  'year': 2007,
  'clues': ['Starring Suriya, dual roles.', 'Asin is the female lead.', 'Hari directed the movie.']},
 {'title': 'Kireedam',
  'year': 2007,
  'clues': ["Starring Ajith Kumar, a police officer's son.",
            "The story follows a family man's downfall.",
            'A. L. Vijay directed the movie.']},
 {'title': 'Subramaniapuram',
  'year': 2008,
  'clues': ['Jai and Sasikumar are among the leads.',
            'The story is set in 1980s Madurai.',
            'M. Sasikumar directed the movie.']},
 {'title': 'Santosh Subramaniam',
  'year': 2008,
  'clues': ['Starring Jayam Ravi, the lead.', 'Genelia is the female lead.', 'M. Raja directed the movie.']},
 {'title': 'Yaaradi Nee Mohini',
  'year': 2008,
  'clues': ['Starring Dhanush, the lead.',
            'Nayanthara is the female lead.',
            'Mithran Jawahar directed the movie.']},
 {'title': 'Dhaam Dhoom',
  'year': 2008,
  'clues': ['Starring Jayam Ravi, the lead.',
            'The story moves between India and Russia.',
            'Jeeva directed the movie.']},
 {'title': 'Silambattam',
  'year': 2008,
  'clues': ['Starring Silambarasan, dual roles.',
            'Sneha and Sana Khan are female leads.',
            'S. Saravanan directed the movie.']},
 {'title': 'Naan Mahaan Alla',
  'year': 2010,
  'clues': ['Starring Karthi, the lead.',
            'The story follows revenge after a tragedy.',
            'Suseenthiran directed the movie.']},
 {'title': 'Paiyaa',
  'year': 2010,
  'clues': ['Starring Karthi, a young man on a road journey.',
            'Tamannaah is the female lead.',
            'N. Lingusamy directed the movie.']},
 {'title': 'Vinnaithaandi Varuvaayaa',
  'year': 2010,
  'clues': ['Starring Silambarasan, Karthik.',
            'Trisha plays Jessie.',
            'Gautham Vasudev Menon directed the movie.']},
 {'title': 'Madrasapattinam',
  'year': 2010,
  'clues': ['Starring Arya, the lead.',
            'The story is set during British-era Madras.',
            'A. L. Vijay directed the movie.']},
 {'title': 'Boss Engira Bhaskaran',
  'year': 2010,
  'clues': ['Starring Arya, Bhaskaran.', 'Nayanthara is the female lead.', 'M. Rajesh directed the movie.']},
 {'title': 'Kalavani',
  'year': 2010,
  'clues': ['Starring Vimal, the lead.',
            'The story is a rural romantic comedy.',
            'A. Sarkunam directed the movie.']},
 {'title': 'Aadukalam',
  'year': 2011,
  'clues': ['Starring Dhanush, a rooster trainer.',
            'The story revolves around cockfighting.',
            'Vetrimaaran directed the movie.']},
 {'title': 'Deiva Thirumagal',
  'year': 2011,
  'clues': ['Starring Vikram, a mentally challenged father.',
            'Anushka Shetty plays a lawyer.',
            'A. L. Vijay directed the movie.']},
 {'title': '7 Aum Arivu',
  'year': 2011,
  'clues': ['Starring Suriya, a descendant of Bodhidharma.',
            'The story involves biological warfare.',
            'A. R. Murugadoss directed the movie.']},
 {'title': 'Ko',
  'year': 2011,
  'clues': ['Starring Jiiva, a photojournalist.',
            'The story involves politics and an election.',
            'K. V. Anand directed the movie.']},
 {'title': 'Mouna Guru',
  'year': 2011,
  'clues': ['Starring Arulnithi, the lead.',
            'The story is a crime thriller.',
            'Santha Kumar directed the movie.']},
 {'title': 'Rowthiram',
  'year': 2011,
  'clues': ['Starring Jiiva, the lead.',
            'The story centers on anger and revenge.',
            'Gokul directed the movie.']},
 {'title': 'Nanban',
  'year': 2012,
  'clues': ['Starring Vijay, Jiiva and Srikanth, friends.',
            'The story is set around engineering college life.',
            'Shankar directed the movie.']},
 {'title': 'Naan Ee',
  'year': 2012,
  'clues': ['Nani appears as the protagonist before reincarnation.',
            'The hero returns as a housefly.',
            'S. S. Rajamouli directed the movie.']},
 {'title': 'Marina',
  'year': 2012,
  'clues': ['Starring Sivakarthikeyan, the lead.',
            'The story is set around Marina Beach.',
            'Pandiraj directed the movie.']},
 {'title': 'Kumki',
  'year': 2012,
  'clues': ['Starring Vikram Prabhu, a mahout.',
            'The story involves elephants and a village.',
            'Prabhu Salomon directed the movie.']},
 {'title': 'Attakathi',
  'year': 2012,
  'clues': ['Starring Dinesh, the lead.',
            "The story follows a young man's romantic misadventures.",
            'Pa. Ranjith directed the movie.']},
 {'title': 'Paradesi',
  'year': 2013,
  'clues': ['Starring Atharvaa, the lead.',
            'The story follows plantation workers.',
            'Bala directed the movie.']},
 {'title': 'Thalaivaa',
  'year': 2013,
  'clues': ['Starring Vijay, a dancer who becomes a leader.',
            'The story involves Mumbai underworld politics.',
            'A. L. Vijay directed the movie.']},
 {'title': 'Maryan',
  'year': 2013,
  'clues': ['Starring Dhanush, a fisherman.',
            'The story is set partly in Africa.',
            'Bharatbala directed the movie.']},
 {'title': 'Endrendrum Punnagai',
  'year': 2013,
  'clues': ['Starring Jiiva, a photographer.',
            'The story follows three close friends.',
            'I. Ahmed directed the movie.']},
 {'title': 'Raja Rani',
  'year': 2013,
  'clues': ['Arya and Nayanthara are leads.',
            'The story explores an arranged marriage.',
            'Atlee directed the movie.']},
 {'title': 'Varuthapadatha Valibar Sangam',
  'year': 2013,
  'clues': ['Starring Sivakarthikeyan, Bosepandi.',
            'The movie is a rural comedy.',
            'Ponram directed the movie.']},
 {'title': 'D-Day',
  'year': 2013,
  'clues': ['Starring Vijay Sethupathi, a supporting role.',
            'The story involves an Indian intelligence mission.',
            'Nikhil Advani directed the movie.']},
 {'title': 'Arrambam',
  'year': 2013,
  'clues': ['Starring Ajith Kumar, a mysterious man.',
            'The story involves revenge and cybercrime.',
            'Vishnuvardhan directed the movie.']},
 {'title': 'Jigarthanda',
  'year': 2014,
  'clues': ['Starring Siddharth, an aspiring filmmaker.',
            'Bobby Simha plays a gangster.',
            'Karthik Subbaraj directed the movie.']},
 {'title': 'Velaiilla Pattadhari',
  'year': 2014,
  'clues': ['Starring Dhanush, an unemployed civil engineer.',
            'The story focuses on unemployment and family.',
            'Velraj directed the movie.']},
 {'title': 'Madras',
  'year': 2014,
  'clues': ['Starring Karthi, the lead.',
            'The story revolves around a political wall.',
            'Pa. Ranjith directed the movie.']},
 {'title': 'Goli Soda',
  'year': 2014,
  'clues': ['The story follows four teenage boys.',
            'The boys work in a market.',
            'Vijay Milton directed the movie.']},
 {'title': 'Maan Karate',
  'year': 2014,
  'clues': ['Starring Sivakarthikeyan, the lead.',
            'The story combines boxing and comedy.',
            'Thirukumaran directed the movie.']},
 {'title': 'Arima Nambi',
  'year': 2014,
  'clues': ['Starring Vikram Prabhu, the lead.',
            'The story is a thriller involving technology.',
            'Anand Shankar directed the movie.']},
 {'title': 'Kaaviya Thalaivan',
  'year': 2014,
  'clues': ['Starring Siddharth and Prithviraj.',
            'The story is set in the world of theatre.',
            'Vasanthabalan directed the movie.']},
 {'title': 'Papanasam',
  'year': 2015,
  'clues': ['Starring Kamal Haasan, a cable operator.',
            'The story involves a family hiding a crime.',
            'Jeethu Joseph directed the movie.']},
 {'title': 'I',
  'year': 2015,
  'clues': ['Starring Vikram, a bodybuilder and model.',
            'The story involves revenge and transformation.',
            'Shankar directed the movie.']},
 {'title': 'Yennai Arindhaal',
  'year': 2015,
  'clues': ['Starring Ajith Kumar, a police officer.',
            'Trisha and Anushka are female leads.',
            'Gautham Vasudev Menon directed the movie.']},
 {'title': 'OK Kanmani',
  'year': 2015,
  'clues': ['Starring Dulquer Salmaan and Nithya Menen.',
            'The story explores a live-in relationship.',
            'Mani Ratnam directed the movie.']},
 {'title': 'Kaaka Muttai',
  'year': 2015,
  'clues': ['Two boys dream of eating a pizza.',
            'The story focuses on children from a slum.',
            'M. Manikandan directed the movie.']},
 {'title': 'Demonte Colony',
  'year': 2015,
  'clues': ['The story follows four friends.',
            'The movie is a supernatural horror thriller.',
            'R. Ajay Gnanamuthu directed the movie.']},
 {'title': 'Indru Netru Naalai',
  'year': 2015,
  'clues': ['Starring Vishnu Vishal, the lead.',
            'The story involves a time machine.',
            'R. Ravikumar directed the movie.']},
 {'title': 'Uttama Villain',
  'year': 2015,
  'clues': ['Starring Kamal Haasan, a film star and a performer.',
            'The story explores mortality and art.',
            'Ramesh Aravind directed the movie.']},
 {'title': 'Rajathandhiram',
  'year': 2015,
  'clues': ['Starring Veera Bahu, the lead.',
            'The story involves a heist.',
            'A. G. Amid directed the movie.']},
 {'title': 'Irudhi Suttru',
  'year': 2016,
  'clues': ['Starring Madhavan, a boxing coach.',
            'Ritika Singh plays a boxer.',
            'Sudha Kongara directed the movie.']},
 {'title': 'Theri',
  'year': 2016,
  'clues': ['Starring Vijay, a police officer.',
            'Samantha and Amy Jackson are female leads.',
            'Atlee directed the movie.']},
 {'title': 'Kabali',
  'year': 2016,
  'clues': ['Starring Rajinikanth, a Malaysian Tamil gangster.',
            'The story involves an imprisoned crime boss.',
            'Pa. Ranjith directed the movie.']},
 {'title': '24',
  'year': 2016,
  'clues': ['Starring Suriya, multiple roles.',
            'The story involves a time-traveling watch.',
            'Vikram K. Kumar directed the movie.']},
 {'title': 'Visaranai',
  'year': 2016,
  'clues': ['The story follows migrant workers facing police brutality.',
            'The movie is based on a novel.',
            'Vetrimaaran directed the movie.']},
 {'title': 'Kodi',
  'year': 2016,
  'clues': ['Starring Dhanush, dual roles.',
            'The story involves politics.',
            'R. S. Durai Senthilkumar directed the movie.']},
 {'title': 'Aandavan Kattalai',
  'year': 2016,
  'clues': ['Starring Vijay Sethupathi, the lead.',
            'The story follows a man seeking a visa.',
            'M. Manikandan directed the movie.']},
 {'title': 'Maanagaram',
  'year': 2017,
  'clues': ['The story connects several strangers in Chennai.',
            'The movie is a hyperlink thriller.',
            'Lokesh Kanagaraj directed the movie.']},
 {'title': 'Vikram Vedha',
  'year': 2017,
  'clues': ['Starring R. Madhavan, a police officer.',
            'Vijay Sethupathi plays a gangster.',
            'Pushkar–Gayathri directed the movie.']},
 {'title': 'Mersal',
  'year': 2017,
  'clues': ['Starring Vijay, triple roles.',
            'The story involves medical corruption.',
            'Atlee directed the movie.']},
 {'title': 'Aramm',
  'year': 2017,
  'clues': ['Starring Nayanthara, a district collector.',
            'The story involves a child trapped in a borewell.',
            'Gopi Nainar directed the movie.']},
 {'title': 'Meyaadha Maan',
  'year': 2017,
  'clues': ['Starring Vaibhav, the lead.',
            'The story is a romantic comedy.',
            'Rathna Kumar directed the movie.']},
 {'title': 'Taramani',
  'year': 2017,
  'clues': ['Starring Vasanth Ravi, the lead.',
            'Andrea Jeremiah is the female lead.',
            'Ram directed the movie.']},
 {'title': 'Mupparimanam',
  'year': 2017,
  'clues': ['Starring Shirish, the lead.',
            'The story involves romance and suspense.',
            'Adhiroopan directed the movie.']},
 {'title': 'Imaikkaa Nodigal',
  'year': 2018,
  'clues': ['Starring Nayanthara, a police officer.',
            'The story follows a serial killer case.',
            'R. Ajay Gnanamuthu directed the movie.']},
 {'title': 'Kaala',
  'year': 2018,
  'clues': ['Starring Rajinikanth, a Dharavi leader.',
            'The story involves land rights and politics.',
            'Pa. Ranjith directed the movie.']},
 {'title': '2.0',
  'year': 2018,
  'clues': ['Starring Rajinikanth, a scientist and robot.',
            'Akshay Kumar plays the antagonist.',
            'Shankar directed the movie.']},
 {'title': 'Chekka Chivantha Vaanam',
  'year': 2018,
  'clues': ['Starring Arvind Swamy, STR, Arun Vijay and Vijay Sethupathi.',
            'The story follows a crime family.',
            'Mani Ratnam directed the movie.']},
 {'title': 'Irumbu Thirai',
  'year': 2018,
  'clues': ['Starring Vishal, a soldier turned cybercrime investigator.',
            'Samantha is the female lead.',
            'P. S. Mithran directed the movie.']},
 {'title': 'Merku Thodarchi Malai',
  'year': 2018,
  'clues': ['Starring Antony, the lead.',
            'The story follows plantation workers.',
            'Lenin Bharathi directed the movie.']},
 {'title': 'Super Deluxe',
  'year': 2019,
  'clues': ['Starring Vijay Sethupathi, Shilpa.',
            'The film follows several interconnected stories.',
            'Thiagarajan Kumararaja directed the movie.']},
 {'title': 'Petta',
  'year': 2019,
  'clues': ['Starring Rajinikanth, Kaali.',
            'The story involves a hostel warden with a hidden past.',
            'Karthik Subbaraj directed the movie.']},
 {'title': 'Nerkonda Paarvai',
  'year': 2019,
  'clues': ['Starring Ajith Kumar, a lawyer.',
            'The story addresses consent and justice.',
            'H. Vinoth directed the movie.']},
 {'title': 'Bigil',
  'year': 2019,
  'clues': ['Starring Vijay, a former footballer.',
            'Nayanthara is the female lead.',
            'Atlee directed the movie.']},
 {'title': 'Dharala Prabhu',
  'year': 2020,
  'clues': ['Starring Harish Kalyan, the lead.',
            'The story involves sperm donation.',
            'Krishna Marimuthu directed the movie.']},
 {'title': 'Kannum Kannum Kollaiyadithaal',
  'year': 2020,
  'clues': ['Starring Dulquer Salmaan and Rakshan.',
            'The story involves a group of con artists.',
            'Desingh Periyasamy directed the movie.']},
 {'title': 'Ka/Pae. Ranasingam',
  'year': 2020,
  'clues': ['Starring Vijay Sethupathi and Aishwarya Rajesh.',
            'The story focuses on land and government bureaucracy.',
            'P. Virumandi directed the movie.']},
 {'title': 'Mookuthi Amman',
  'year': 2020,
  'clues': ['Starring Nayanthara, a goddess.',
            'R. J. Balaji plays the male lead.',
            'R. J. Balaji and N. J. Saravanan directed the movie.']},
 {'title': 'Paava Kadhaigal',
  'year': 2020,
  'clues': ['The anthology explores family and social issues.',
            'It contains four interconnected stories.',
            'The segments were directed by four filmmakers.']},
 {'title': 'Sarpatta Parambarai',
  'year': 2021,
  'clues': ['Starring Arya, a boxer.',
            'The story is set in 1970s North Madras.',
            'Pa. Ranjith directed the movie.']},
 {'title': 'Maanaadu',
  'year': 2021,
  'clues': ['Starring Silambarasan, Abdul Khaaliq.',
            'The story involves a time-loop.',
            'Venkat Prabhu directed the movie.']},
 {'title': 'Karnan',
  'year': 2021,
  'clues': ['Starring Dhanush, the lead.',
            'The story focuses on oppression in a village.',
            'Mari Selvaraj directed the movie.']},
 {'title': 'Writer',
  'year': 2021,
  'clues': ['Starring Samuthirakani, a police officer.',
            'The story examines the police system.',
            'Franklin Jacob directed the movie.']},
 {'title': 'Nenjamundu Nermaiyundu Odu Raja',
  'year': 2019,
  'clues': ['Starring Rio Raj, the lead.',
            'The movie is a comedy.',
            'Karthik Venugopal directed the movie.']},
 {'title': 'Saani Kaayidham',
  'year': 2022,
  'clues': ['Starring Keerthy Suresh and Selvaraghavan.',
            'The story follows a revenge journey.',
            'Arun Matheswaran directed the movie.']},
 {'title': 'Mahaan',
  'year': 2022,
  'clues': ['Starring Vikram and Dhruv Vikram, father and son.',
            'The story involves a clash between ideology and ambition.',
            'Karthik Subbaraj directed the movie.']},
 {'title': 'Nitham Oru Vaanam',
  'year': 2022,
  'clues': ['Starring Ashok Selvan, the lead.',
            'The story involves three narratives.',
            'R. Karthik directed the movie.']},
 {'title': 'Taanakkaran',
  'year': 2022,
  'clues': ['Starring Vikram Prabhu, a trainee police officer.',
            'The story is set in a police training academy.',
            'Tamizh directed the movie.']},
 {'title': 'Gargi',
  'year': 2022,
  'clues': ['Starring Sai Pallavi, a schoolteacher.',
            'The story follows a sexual assault case and trial.',
            'Gautham Ramachandran directed the movie.']},
 {'title': 'Ponniyin Selvan: I',
  'year': 2022,
  'clues': ['Vikram, Karthi and Jayam Ravi are among the leads.',
            "The story is based on Kalki's historical novel.",
            'Mani Ratnam directed the movie.']},
 {'title': 'Ponniyin Selvan: II',
  'year': 2023,
  'clues': ['Vikram, Karthi and Jayam Ravi return.',
            'The story continues the Chola-era saga.',
            'Mani Ratnam directed the movie.']},
 {'title': 'Maamannan',
  'year': 2023,
  'clues': ['Starring Vadivelu, an important political leader.',
            'Fahadh Faasil plays the antagonist.',
            'Mari Selvaraj directed the movie.']},
 {'title': 'Viduthalai Part 1',
  'year': 2023,
  'clues': ['Starring Soori, a police constable.',
            'Vijay Sethupathi plays Perumal Vaathiyar.',
            'Vetrimaaran directed the movie.']},
 {'title': 'Por Thozhil',
  'year': 2023,
  'clues': ['Starring R. Sarathkumar and Ashok Selvan, police officers.',
            'The story follows a serial killer investigation.',
            'Vignesh Raja and T. Senthil directed the movie.']},
 {'title': 'Chithha',
  'year': 2023,
  'clues': ['Starring Siddharth, the lead.',
            'The story follows a missing child investigation.',
            'S. U. Arun Kumar directed the movie.']},
 {'title': 'Mark Antony',
  'year': 2023,
  'clues': ['Starring Vishal and S. J. Suryah, dual roles.',
            'The story involves time travel through a telephone.',
            'Adhik Ravichandran directed the movie.']},
 {'title': 'Jigarthanda DoubleX',
  'year': 2023,
  'clues': ['Starring Raghava Lawrence and S. J. Suryah.',
            'The story combines gangster drama and filmmaking.',
            'Karthik Subbaraj directed the movie.']},
 {'title': 'Ayalaan',
  'year': 2024,
  'clues': ['Starring Sivakarthikeyan, the lead.',
            'The story features an alien companion.',
            'R. Ravikumar directed the movie.']},
 {'title': 'Captain Miller',
  'year': 2024,
  'clues': ['Starring Dhanush, a former soldier.',
            'The story is set across colonial-era India.',
            'Arun Matheswaran directed the movie.']},
 {'title': 'Aranmanai 4',
  'year': 2024,
  'clues': ['Starring Sundar C., the lead.',
            'Tamannaah and Raashi Khanna are female leads.',
            'The movie is a horror comedy.']},
 {'title': 'Garudan',
  'year': 2024,
  'clues': ['Starring Soori, the lead.',
            'The story explores friendship and betrayal.',
            'R. S. Durai Senthilkumar directed the movie.']},
 {'title': 'Maharaja',
  'year': 2024,
  'clues': ['Starring Vijay Sethupathi, the lead.',
            'The story revolves around a barber seeking revenge.',
            'Nithilan Saminathan directed the movie.']},
 {'title': 'Amaran',
  'year': 2024,
  'clues': ['Starring Sivakarthikeyan, Major Mukund Varadarajan.',
            'The story is based on a real army officer.',
            'Rajkumar Periasamy directed the movie.']},
 {'title': 'Meiyazhagan',
  'year': 2024,
  'clues': ['Starring Karthi and Arvind Swamy.',
            'The story follows two relatives reconnecting.',
            'C. Prem Kumar directed the movie.']},
 {'title': 'Lubber Pandhu',
  'year': 2024,
  'clues': ['Starring Harish Kalyan and Attakathi Dinesh.',
            'The story revolves around street cricket.',
            'Tamizharasan Pachamuthu directed the movie.']},
 {'title': 'Raayan',
  'year': 2024,
  'clues': ['Starring Dhanush, the lead.',
            'The story follows a man protecting his family.',
            'Dhanush directed the movie.']},
 {'title': 'Kanguva',
  'year': 2024,
  'clues': ['Starring Suriya, multiple roles.',
            'The story spans historical and modern timelines.',
            'Siva directed the movie.']},
 {'title': 'Boat',
  'year': 2024,
  'clues': ['The story follows survivors stranded at sea.',
            'The film is set during World War II.',
            'M. S. Bhaskar is among the cast.']},
 {'title': 'Star',
  'year': 2024,
  'clues': ['Starring Kavin, a young aspiring actor.',
            'The story follows his journey in cinema.',
            'Elan directed the movie.']},
 {'title': 'Dada',
  'year': 2023,
  'clues': ['Starring Kavin, a young father.',
            'The story follows a single father raising his child.',
            'Ganesh K. Babu directed the movie.']},
 {'title': 'Love Today',
  'year': 2022,
  'clues': ['Starring Pradeep Ranganathan, the lead.',
            'A couple swap their phones for a day.',
            'Pradeep Ranganathan directed the movie.']},
 {'title': 'Sachein',
  'year': 2005,
  'clues': ['Starring Vijay, a college student.',
            'Genelia is the female lead.',
            'John Mahendran directed the movie.']},
 {'title': 'Azhagiya Tamil Magan',
  'year': 2007,
  'clues': ['Starring Vijay, dual roles.',
            'The story involves a man with visions of the future.',
            'Bharathan directed the movie.']},
 {'title': 'Kuruvi',
  'year': 2008,
  'clues': ['Starring Vijay, a mechanic and thief.',
            'Trisha is the female lead.',
            'Dharani directed the movie.']},
 {'title': 'Villu',
  'year': 2009,
  'clues': ['Starring Vijay, the lead.',
            'The story involves a police family.',
            'Prabhu Deva directed the movie.']},
 {'title': 'Sura',
  'year': 2010,
  'clues': ['Starring Vijay, a fisherman.',
            'The story involves protecting a coastal village.',
            'S. P. Rajkumar directed the movie.']},
 {'title': 'Velayudham',
  'year': 2011,
  'clues': ['Starring Vijay, a milkman who becomes a vigilante.',
            'The story involves fighting corruption.',
            'Mohan Raja directed the movie.']},
 {'title': 'Jilla',
  'year': 2014,
  'clues': ['Starring Vijay, Sakthi.',
            'Mohanlal plays his father figure.',
            'R. T. Neason directed the movie.']},
 {'title': 'Puli',
  'year': 2015,
  'clues': ['Starring Vijay, a warrior in a fantasy kingdom.',
            'Sridevi plays the antagonist.',
            'Chimbu Deven directed the movie.']},
 {'title': 'Bairavaa',
  'year': 2017,
  'clues': ['Starring Vijay, a collection agent.',
            'The story involves a corrupt educational institution.',
            'Bharathan directed the movie.']},
 {'title': 'Sarkar',
  'year': 2018,
  'clues': ['Starring Vijay, a corporate CEO.',
            'The story focuses on election rights.',
            'A. R. Murugadoss directed the movie.']},
 {'title': 'Varisu',
  'year': 2023,
  'clues': ['Starring Vijay, a family business heir.',
            'The story revolves around a family business.',
            'Vamshi Paidipally directed the movie.']},
 {'title': 'Beast',
  'year': 2022,
  'clues': ['Starring Vijay, a former RAW agent.',
            'The story involves a shopping mall hostage situation.',
            'Nelson directed the movie.']},
 {'title': 'Kushi',
  'year': 2023,
  'clues': ['Starring Vijay Deverakonda and Samantha.',
            'The story is a romantic comedy.',
            'Shiva Nirvana directed the movie.']},
 {'title': 'Ayogya',
  'year': 2019,
  'clues': ['Starring Vishal, a corrupt police officer.',
            'The story turns into a fight for justice.',
            'Venkat Mohan directed the movie.']},
 {'title': 'Enemy',
  'year': 2021,
  'clues': ['Starring Vishal and Arya, brothers.',
            'The story involves rivalry and revenge.',
            'Anand Shankar directed the movie.']},
 {'title': 'Sandakozhi 2',
  'year': 2018,
  'clues': ['Vishal returns as Balu.',
            'Keerthy Suresh is the female lead.',
            'N. Lingusamy directed the movie.']},
 {'title': 'Thupparivaalan',
  'year': 2017,
  'clues': ['Starring Vishal, a private detective.',
            'The story follows a murder investigation.',
            'Mysskin directed the movie.']},
 {'title': 'Kathakali',
  'year': 2016,
  'clues': ['Starring Vishal, the lead.',
            'The story unfolds over a single night.',
            'Pandiraj directed the movie.']},
 {'title': 'Poojai',
  'year': 2014,
  'clues': ['Starring Vishal, a lorry driver.',
            'The story involves a family feud.',
            'Hari directed the movie.']},
 {'title': 'Avan Ivan',
  'year': 2011,
  'clues': ['Starring Vishal and Arya, brothers.',
            'The story is set in rural Tamil Nadu.',
            'Bala directed the movie.']},
 {'title': 'Dev',
  'year': 2019,
  'clues': ['Starring Karthi, an adventurous young man.',
            'The story involves travel and romance.',
            'Rajath Ravishankar directed the movie.']},
 {'title': 'Sulthan',
  'year': 2021,
  'clues': ['Starring Karthi, a man protecting villagers.',
            'The story involves a group of rowdies.',
            'Bakkiyaraj Kannan directed the movie.']},
 {'title': 'Viruman',
  'year': 2022,
  'clues': ['Starring Karthi, a rural young man.',
            'The story focuses on family conflict.',
            'M. Muthaiah directed the movie.']},
 {'title': 'Japan',
  'year': 2023,
  'clues': ['Starring Karthi, a notorious thief.',
            'The story is a crime comedy.',
            'Raju Murugan directed the movie.']},
 {'title': 'Kaashmora',
  'year': 2016,
  'clues': ['Starring Karthi, a con artist.',
            'The movie includes a historical horror storyline.',
            'Gokul directed the movie.']},
 {'title': 'Komban',
  'year': 2015,
  'clues': ['Starring Karthi, a rural man.',
            'The story focuses on family and village rivalry.',
            'M. Muthaiah directed the movie.']},
 {'title': 'Kadaikutty Singam',
  'year': 2018,
  'clues': ['Starring Karthi, a farmer.',
            'The story revolves around a large family.',
            'Pandiraj directed the movie.']},
 {'title': 'Si3',
  'year': 2017,
  'clues': ['Starring Suriya, police officer Durai Singam.',
            'The story is a police action thriller.',
            'Hari directed the movie.']},
 {'title': 'NGK',
  'year': 2019,
  'clues': ['Starring Suriya, an idealistic man entering politics.',
            'Sai Pallavi and Rakul Preet Singh are female leads.',
            'Selvaraghavan directed the movie.']},
 {'title': 'Etharkkum Thunindhavan',
  'year': 2022,
  'clues': ['Starring Suriya, a lawyer.',
            'The story tackles abuse and revenge.',
            'Pandiraj directed the movie.']},
 {'title': 'Massu Engira Masilamani',
  'year': 2015,
  'clues': ['Starring Suriya, a man who can see ghosts.',
            'The movie mixes horror and comedy.',
            'Venkat Prabhu directed the movie.']},
 {'title': 'Anjaan',
  'year': 2014,
  'clues': ['Starring Suriya, a gangster.',
            'The story is set partly in Mumbai.',
            'N. Lingusamy directed the movie.']},
 {'title': 'Singam 2',
  'year': 2013,
  'clues': ['Suriya returns as Durai Singam.',
            'The story involves an undercover police mission.',
            'Hari directed the movie.']},
 {'title': 'Singam 3',
  'year': 2017,
  'clues': ['Suriya returns as Durai Singam.',
            'The investigation takes him to Andhra Pradesh.',
            'Hari directed the movie.']},
 {'title': 'Aayutha Ezhuthu',
  'year': 2004,
  'clues': ['Starring Suriya, Madhavan and Siddharth.',
            'Three lives intersect around political events.',
            'Mani Ratnam directed the movie.']},
 {'title': 'Velaiilla Pattadhari 2',
  'year': 2017,
  'clues': ['Starring Dhanush, an unemployed engineer.',
            'Kajol plays the antagonist.',
            'Soundarya Rajinikanth directed the movie.']},
 {'title': 'Pattas',
  'year': 2020,
  'clues': ['Starring Dhanush, a martial artist.',
            'The story involves an ancient fighting style.',
            'R. S. Durai Senthilkumar directed the movie.']},
 {'title': 'Atrangi Re',
  'year': 2021,
  'clues': ['Starring Dhanush, a magician.',
            'The story is a romantic drama involving a complicated relationship.',
            'Aanand L. Rai directed the movie.']},
 {'title': 'Naane Varuvean',
  'year': 2022,
  'clues': ['Starring Dhanush, dual roles.',
            'The story is a psychological thriller.',
            'Selvaraghavan directed the movie.']},
 {'title': 'Vaathi',
  'year': 2023,
  'clues': ['Starring Dhanush, a teacher.',
            'The story focuses on education and inequality.',
            'Venky Atluri directed the movie.']},
 {'title': 'Nilavukku Enmel Ennadi Kobam',
  'year': 2025,
  'clues': ['The story follows young adults and relationships.',
            'It is a romantic comedy-drama.',
            'Dhanush directed the movie.']},
 {'title': 'Kubera',
  'year': 2025,
  'clues': ['Starring Dhanush, a homeless man.',
            'The story involves wealth and corruption.',
            'Sekhar Kammula directed the movie.']},
 {'title': 'Mayakkam Enna',
  'year': 2011,
  'clues': ['Starring Dhanush, an aspiring photographer.',
            'The story follows his relationship and career struggles.',
            'Selvaraghavan directed the movie.']},
 {'title': 'Uthamaputhiran',
  'year': 2010,
  'clues': ['Starring Dhanush, the lead.',
            'The story is a romantic comedy.',
            'Mithran Jawahar directed the movie.']},
 {'title': '3',
  'year': 2012,
  'clues': ['Starring Dhanush, Ram.',
            'The story explores love and mental health.',
            'Aishwarya Rajinikanth directed the movie.']},
 {'title': 'VIP',
  'year': 2014,
  'clues': ['Starring Dhanush, Raghuvaran.',
            'The story follows an unemployed engineer.',
            'Velraj directed the movie.']},
 {'title': 'Kakki Sattai',
  'year': 2015,
  'clues': ['Starring Sivakarthikeyan, a police officer.',
            'The story involves organ trafficking.',
            'R. S. Durai Senthilkumar directed the movie.']},
 {'title': 'Remo',
  'year': 2016,
  'clues': ['Sivakarthikeyan disguises himself as a nurse.',
            'Keerthy Suresh is the female lead.',
            'Bakkiyaraj Kannan directed the movie.']},
 {'title': 'Velaikkaran',
  'year': 2017,
  'clues': ['Starring Sivakarthikeyan, a worker.',
            'The story focuses on corporate food practices.',
            'M. Mohan Raja directed the movie.']},
 {'title': 'Seema Raja',
  'year': 2018,
  'clues': ['Starring Sivakarthikeyan, a village chieftain.',
            'The story is a rural action comedy.',
            'Ponram directed the movie.']},
 {'title': 'Hero',
  'year': 2019,
  'clues': ['Starring Sivakarthikeyan, a young inventor.',
            'The story criticizes the education system.',
            'P. S. Mithran directed the movie.']},
 {'title': 'Mr. Local',
  'year': 2019,
  'clues': ['Starring Sivakarthikeyan and Nayanthara.',
            'The story is a romantic comedy.',
            'M. Rajesh directed the movie.']},
 {'title': 'Prince',
  'year': 2022,
  'clues': ['Starring Sivakarthikeyan, a teacher.',
            'The story is a romantic comedy.',
            'Anudeep K. V. directed the movie.']},
 {'title': 'Maaveeran',
  'year': 2023,
  'clues': ['Starring Sivakarthikeyan, a comic artist.',
            'The hero hears a mysterious voice.',
            'Madonne Ashwin directed the movie.']},
 {'title': 'Seemaraja',
  'year': 2018,
  'clues': ['Starring Sivakarthikeyan, a village leader.',
            'The story includes a historical flashback.',
            'Ponram directed the movie.']},
 {'title': 'Ethir Neechal',
  'year': 2013,
  'clues': ['Starring Sivakarthikeyan, a young man.',
            'The story involves athletics and self-confidence.',
            'R. S. Durai Senthilkumar directed the movie.']},
 {'title': 'Kedi Billa Killadi Ranga',
  'year': 2013,
  'clues': ['Starring Sivakarthikeyan and Vimal.',
            'The story follows two unemployed friends.',
            'Pandiraj directed the movie.']},
 {'title': 'Rajinimurugan',
  'year': 2016,
  'clues': ['Starring Sivakarthikeyan, Rajinimurugan.',
            'The story is a rural comedy.',
            'Ponram directed the movie.']},
 {'title': 'Laabam',
  'year': 2021,
  'clues': ['Starring Vijay Sethupathi, a farmer.',
            'The story focuses on agriculture and corporate control.',
            'S. P. Jananathan directed the movie.']},
 {'title': 'Kadhalum Kadandhu Pogum',
  'year': 2016,
  'clues': ['Starring Vijay Sethupathi, a local rowdy.',
            'Madonna Sebastian is the female lead.',
            'Nalan Kumarasamy directed the movie.']},
 {'title': 'Orange Mittai',
  'year': 2015,
  'clues': ['Starring Vijay Sethupathi, an eccentric ambulance patient.',
            'The movie is a comedy-drama.',
            'Biju Viswanath directed the movie.']},
 {'title': 'Dharma Durai',
  'year': 2016,
  'clues': ['Starring Vijay Sethupathi, a doctor.',
            'The story follows his journey after leaving his family.',
            'Seenu Ramasamy directed the movie.']},
 {'title': 'Sethupathi',
  'year': 2016,
  'clues': ['Starring Vijay Sethupathi, a police officer.',
            'The story involves a corrupt police officer and a murder case.',
            'S. U. Arun Kumar directed the movie.']},
 {'title': 'Naanum Rowdy Dhaan',
  'year': 2015,
  'clues': ['Starring Vijay Sethupathi, Pandian.',
            'Nayanthara plays a woman seeking revenge.',
            'Vignesh Shivan directed the movie.']},
 {'title': 'Kaathuvaakula Rendu Kaadhal',
  'year': 2022,
  'clues': ['Vijay Sethupathi has two love interests.',
            'Nayanthara and Samantha are female leads.',
            'Vignesh Shivan directed the movie.']},
 {'title': 'Train',
  'year': 2025,
  'clues': ['Starring Vijay Sethupathi, the lead.',
            'The story is a thriller.',
            'Mysskin directed the movie.']},
 {'title': 'Ace',
  'year': 2025,
  'clues': ['Starring Vijay Sethupathi, a man involved in crime.',
            'The story combines crime and comedy.',
            'Arumuga Kumar directed the movie.']},
 {'title': 'Merry Christmas',
  'year': 2024,
  'clues': ['Vijay Sethupathi stars opposite Katrina Kaif.',
            'The story unfolds over one night.',
            'Sriram Raghavan directed the movie.']},
 {'title': 'Viduthalai Part 2',
  'year': 2024,
  'clues': ['Soori continues as Kumaresan.',
            "The story expands Perumal's political journey.",
            'Vetrimaaran directed the movie.']},
 {'title': 'Pisaasu',
  'year': 2014,
  'clues': ['Starring Naga, the lead.',
            'The story involves a mysterious ghost.',
            'Mysskin directed the movie.']},
 {'title': 'Pisasu 2',
  'year': 2024,
  'clues': ['Starring Andrea Jeremiah, the lead.',
            'The story is a supernatural thriller.',
            'Mysskin directed the movie.']},
 {'title': 'Onayum Aattukkuttiyum',
  'year': 2013,
  'clues': ['Starring Sri, the lead.',
            'The story follows a man trying to save a stranger.',
            'Mysskin directed the movie.']},
 {'title': 'Mugamoodi',
  'year': 2012,
  'clues': ['Starring Jiiva, a masked superhero.',
            'The story involves martial arts and crime.',
            'Mysskin directed the movie.']},
 {'title': 'Psycho',
  'year': 2020,
  'clues': ['Starring Udhayanidhi Stalin, a visually impaired man.',
            'The story follows a serial killer investigation.',
            'Mysskin directed the movie.']},
 {'title': 'Dhuruvangal Pathinaaru',
  'year': 2016,
  'clues': ['Starring Rahman, a retired police officer.',
            'The story revisits an unsolved case.',
            'Karthick Naren directed the movie.']},
 {'title': 'Naragasooran',
  'year': 2025,
  'clues': ['The story is a mystery thriller.',
            'Arvind Swamy is among the leads.',
            'Karthick Naren directed the movie.']},
 {'title': 'Iraivi',
  'year': 2016,
  'clues': ['Starring S. J. Suryah, Vijay Sethupathi and Bobby Simha.',
            'The story follows several troubled men.',
            'Karthik Subbaraj directed the movie.']},
 {'title': 'Mercury',
  'year': 2018,
  'clues': ['Starring Prabhu Deva, a mysterious figure.',
            'The film has very little spoken dialogue.',
            'Karthik Subbaraj directed the movie.']},
 {'title': 'Jagame Thandhiram',
  'year': 2021,
  'clues': ['Starring Dhanush, a gangster from Madurai.',
            'The story moves between India and London.',
            'Karthik Subbaraj directed the movie.']},
 {'title': 'Karthikeya 2',
  'year': 2022,
  'clues': ['Nikhil Siddhartha leads.',
            'The story involves a historical mystery.',
            'Chandoo Mondeti directed the movie.']},
 {'title': 'Thavamai Thavamirundhu',
  'year': 2005,
  'clues': ['Starring Cheran, a son and father.',
            'The story focuses on family sacrifice.',
            'Cheran directed the movie.']},
 {'title': 'Maya',
  'year': 2015,
  'clues': ['Starring Nayanthara, the lead.',
            'The story involves a haunted film.',
            'Ashwin Saravanan directed the movie.']},
 {'title': 'Game Over',
  'year': 2019,
  'clues': ['Starring Taapsee Pannu, the lead.',
            'The story involves a woman facing a mysterious threat.',
            'Ashwin Saravanan directed the movie.']},
 {'title': 'Connect',
  'year': 2022,
  'clues': ['Starring Nayanthara, the lead.',
            'The story is a supernatural horror film.',
            'Ashwin Saravanan directed the movie.']},
 {'title': 'Irudhu Suttru',
  'year': 2016,
  'clues': ['Starring Ritika Singh, a boxer.',
            'Madhavan plays her coach.',
            'Sudha Kongara directed the movie.']},
 {'title': 'Sillu Karupatti',
  'year': 2019,
  'clues': ['The film contains four love stories.',
            'The stories explore different forms of love.',
            'Halitha Shameem directed the movie.']},
 {'title': 'Aelay',
  'year': 2021,
  'clues': ['Starring Samuthirakani and Madhumathi.',
            'The story follows a father and son.',
            'Halitha Shameem directed the movie.']},
 {'title': 'Kurangu Bommai',
  'year': 2017,
  'clues': ['Starring Vidharth, the lead.',
            'The story involves a stolen bag and crime.',
            'Nithilan Saminathan directed the movie.']},
 {'title': 'Koozhangal',
  'year': 2021,
  'clues': ['The story follows a father and son.',
            'The film focuses on a journey through a dry landscape.',
            'P. S. Vinothraj directed the movie.']},
 {'title': 'Pebbles',
  'year': 2021,
  'clues': ['The film follows a father and son.',
            'The story is set in rural Tamil Nadu.',
            'P. S. Vinothraj directed the movie.']},
 {'title': 'Maanadu',
  'year': 2021,
  'clues': ['Starring Silambarasan, Abdul Khaaliq.',
            'The protagonist is trapped in a time loop.',
            'Venkat Prabhu directed the movie.']},
 {'title': 'Eeswaran',
  'year': 2021,
  'clues': ['Starring Silambarasan, a village man.',
            'The story involves family and revenge.',
            'Suseenthiran directed the movie.']},
 {'title': 'Vendhu Thanindhathu Kaadu',
  'year': 2022,
  'clues': ['Starring Silambarasan, Muthu.',
            'The story follows his journey from rural Tamil Nadu to Mumbai.',
            'Gautham Vasudev Menon directed the movie.']},
 {'title': 'Pathu Thala',
  'year': 2023,
  'clues': ['Starring Silambarasan, a gangster.',
            'Gautham Karthik plays a police officer.',
            'Obeli N. Krishna directed the movie.']},
 {'title': 'Vaanam',
  'year': 2011,
  'clues': ['Silambarasan is one of the ensemble leads.',
            'The film follows multiple interconnected lives.',
            'Krish Jagarlamudi directed the movie.']},
 {'title': 'Kaalai',
  'year': 2008,
  'clues': ['Starring Silambarasan, a rural youth.',
            'The story is an action drama.',
            'Tarun Gopi directed the movie.']},
 {'title': 'Vaagai Sooda Vaa',
  'year': 2011,
  'clues': ['Starring Vimal, a teacher.',
            'The story is set in a rural village.',
            'A. Sarkunam directed the movie.']},
 {'title': 'Mundhinam Paartheney',
  'year': 2010,
  'clues': ['Santhanam is among the cast.',
            'The movie is a romantic comedy.',
            'Magizh Thirumeni directed the movie.']},
 {'title': 'Kalakalappu',
  'year': 2012,
  'clues': ['Starring Vimal, Shiva and Santhanam.',
            'The story is a comedy set around a restaurant.',
            'Sundar C. directed the movie.']},
 {'title': 'Theeya Velai Seiyyanum Kumaru',
  'year': 2013,
  'clues': ['Starring Siddharth, the lead.',
            'Santhanam plays a relationship advisor.',
            'Sundar C. directed the movie.']},
 {'title': 'Aranmanai',
  'year': 2014,
  'clues': ['Sundar C. leads the cast.',
            'The story involves a haunted mansion.',
            'Sundar C. directed the movie.']},
 {'title': 'Dhilluku Dhuddu',
  'year': 2016,
  'clues': ['Starring Santhanam, the lead.', 'The movie is a horror comedy.', 'Rambala directed the movie.']},
 {'title': 'A1',
  'year': 2019,
  'clues': ['Starring Santhanam, the lead.',
            'The story is a comedy involving romance and crime.',
            'Johnson K. directed the movie.']},
 {'title': 'Dikkiloona',
  'year': 2021,
  'clues': ['Starring Santhanam, multiple roles.',
            'The story involves time travel.',
            'Karthik Yogi directed the movie.']},
 {'title': 'Agent Kannayiram',
  'year': 2022,
  'clues': ['Starring Santhanam, a private detective.',
            'The story is a mystery comedy.',
            'Manoj Beedha directed the movie.']},
 {'title': '80s Buildup',
  'year': 2023,
  'clues': ['Starring Santhanam, the lead.',
            'The movie is a period comedy.',
            'Kalanithan Kalaivanan directed the movie.']},
 {'title': 'DD Returns',
  'year': 2023,
  'clues': ['Starring Santhanam, the lead.',
            'The story involves a haunted house and a treasure.',
            'S. Prem Anand directed the movie.']},
 {'title': 'Vadakkupatti Ramasamy',
  'year': 2024,
  'clues': ['Starring Santhanam, a village man.',
            'The story is a comedy about superstition.',
            'Karthik Yogi directed the movie.']},
 {'title': 'Madagascar',
  'year': 2024,
  'clues': ['The movie is a Tamil comedy adventure.',
            'The story involves a group facing unexpected trouble.',
            'A. M. R. Ramesh directed the movie.']},
 {'title': 'Comali',
  'year': 2019,
  'clues': ['Jayam Ravi wakes after years in a coma.',
            'The story contrasts old and new technology.',
            'Pradeep Ranganathan directed the movie.']},
 {'title': 'Thani Oruvan',
  'year': 2015,
  'clues': ['Starring Jayam Ravi, a police officer.',
            'Arvind Swamy plays the antagonist.',
            'Mohan Raja directed the movie.']},
 {'title': 'Miruthan',
  'year': 2016,
  'clues': ['Starring Jayam Ravi, a traffic police officer.',
            'The story involves a zombie outbreak.',
            'Shakti Soundar Rajan directed the movie.']},
 {'title': 'Tik Tik Tik',
  'year': 2018,
  'clues': ['Starring Jayam Ravi, an astronaut.',
            'The story involves a space mission.',
            'Shakti Soundar Rajan directed the movie.']},
 {'title': 'Adanga Maru',
  'year': 2018,
  'clues': ['Starring Jayam Ravi, a police officer.',
            'The story involves police corruption.',
            'Ravichandran directed the movie.']},
 {'title': 'Bogan',
  'year': 2017,
  'clues': ['Starring Jayam Ravi and Arvind Swamy.',
            'The story involves body swapping.',
            'Lakshman directed the movie.']},
 {'title': 'Romeo Juliet',
  'year': 2015,
  'clues': ['Starring Jayam Ravi and Hansika.',
            'The story is a romantic comedy.',
            'Lakshman directed the movie.']},
 {'title': 'Kadhal Virus', 'year': 2002, 'clues': ['Starring Richard, romantic drama directed by Kathir.']},
 {'title': 'Bagavathi',
  'year': 2002,
  'clues': ['Starring Vijay, action drama about a man protecting his family.']},
 {'title': 'Ivan',
  'year': 2002,
  'clues': ['Starring Prashanth, romantic comedy directed by K. Selva Bharathy.']},
 {'title': 'Pammal K. Sambandam',
  'year': 2002,
  'clues': ['Starring Kamal Haasan, comedy about a stuntman and marriage.']},
 {'title': 'April Maadhathil',
  'year': 2002,
  'clues': ['Starring Srikanth, college friendship and romance drama.']},
 {'title': 'Thiruda Thirudi', 'year': 2003, 'clues': ['Starring Dhanush and Chaya Singh, romantic comedy.']},
 {'title': 'Saamy', 'year': 2003, 'clues': ['Starring Vikram, police action movie set around Tirunelveli.']},
 {'title': 'Dhool', 'year': 2003, 'clues': ['Starring Vikram and Jyothika, political action entertainer.']},
 {'title': 'Jay Jay',
  'year': 2003,
  'clues': ['Starring Madhavan and Amoga, romantic comedy directed by Saran.']},
 {'title': 'Aalavandhan', 'year': 2003, 'clues': ['Starring Kamal Haasan, psychological action thriller.']},
 {'title': 'Madurey', 'year': 2004, 'clues': ['Starring Vijay, action movie with a police officer.']},
 {'title': 'Anbe Vaa',
  'year': 2005,
  'clues': ['Starring Vijay, romantic comedy with a hill-station setting.']},
 {'title': 'Thimiru',
  'year': 2006,
  'clues': ['Starring Vishal, action drama about a medical student and revenge.']},
 {'title': 'Unakkum Enakkum',
  'year': 2006,
  'clues': ['Starring Jayam Ravi and Trisha, romantic family drama.']},
 {'title': 'Mozhi', 'year': 2007, 'clues': ['Starring Prithviraj and Jyothika, heartwarming romance.']},
 {'title': 'Deepavali', 'year': 2007, 'clues': ['Starring Jayam Ravi and Bhavana, romantic drama.']},
 {'title': 'Aegan',
  'year': 2008,
  'clues': ['Starring Ajith Kumar, action comedy about an undercover police officer.']},
 {'title': 'Jayam Kondaan', 'year': 2008, 'clues': ['Starring Vinay Rai, family drama and revenge story.']},
 {'title': 'Naan Kadavul',
  'year': 2009,
  'clues': ['Starring Arya, dark drama involving an Aghori and abandoned people.']},
 {'title': 'Pasanga', 'year': 2009, 'clues': ['Starring newcomers, school friendship and childhood drama.']},
 {'title': 'Kanden Kadhalai', 'year': 2009, 'clues': ['Starring Bharath and Tamannaah, romantic comedy.']},
 {'title': 'Eeram',
  'year': 2009,
  'clues': ['Starring Aadhi, supernatural thriller involving a haunted apartment.']},
 {'title': 'Masilamani', 'year': 2009, 'clues': ['Starring Nakul, romantic action comedy.']},
 {'title': 'Renigunta', 'year': 2009, 'clues': ['Starring Johnny, crime drama about young criminals.']},
 {'title': 'Vamsam', 'year': 2010, 'clues': ['Starring Arulnithi, rural family revenge drama.']},
 {'title': 'Mynaa', 'year': 2010, 'clues': ['Starring Vidharth and Amala Paul, emotional rural romance.']},
 {'title': 'Baana Kaathadi', 'year': 2010, 'clues': ['Starring Adharvaa and Samantha, youth romance.']},
 {'title': 'Engeyum Eppodhum',
  'year': 2011,
  'clues': ['Starring Jai and Anjali, two romances and a bus accident.']},
 {'title': '7aum Arivu',
  'year': 2011,
  'clues': ['Starring Suriya, martial arts and genetic-memory science fiction.']},
 {'title': 'Kullanari Koottam', 'year': 2011, 'clues': ['Starring Vishnu Vishal, romantic comedy.']},
 {'title': 'Maattrraan', 'year': 2012, 'clues': ['Starring Suriya in dual roles, medical-action thriller.']},
 {'title': 'Pizza 2: The Villa',
  'year': 2013,
  'clues': ['Starring Ashok Selvan, supernatural mystery thriller.']},
 {'title': 'Pandianadu', 'year': 2013, 'clues': ['Starring Vishal, action drama about family revenge.']},
 {'title': 'Kadal', 'year': 2013, 'clues': ['Starring Gautham Karthik and Thulasi Nair, coastal drama.']},
 {'title': 'Neram',
  'year': 2013,
  'clues': ['Starring Nivin Pauly and Nazriya, comedy thriller about timing.']},
 {'title': 'David', 'year': 2013, 'clues': ['Starring Vikram and Jiiva, two interconnected stories.']},
 {'title': 'Thegidi',
  'year': 2014,
  'clues': ['Starring Ashok Selvan, mystery thriller involving a private investigator.']},
 {'title': 'Mundasupatti',
  'year': 2014,
  'clues': ['Starring Vishnu Vishal, period comedy with superstition.']},
 {'title': 'Kaaki Sattai', 'year': 2015, 'clues': ['Starring Sivakarthikeyan, police action comedy.']},
 {'title': 'Darling', 'year': 2015, 'clues': ['Starring G. V. Prakash Kumar, horror comedy.']},
 {'title': 'Manithan', 'year': 2016, 'clues': ['Starring Udhayanidhi Stalin, courtroom comedy drama.']},
 {'title': 'Achcham Yenbadhu Madamaiyada',
  'year': 2016,
  'clues': ['Starring Silambarasan, road-trip romance and action.']},
 {'title': 'Vivegam', 'year': 2017, 'clues': ['Starring Ajith Kumar, international spy action thriller.']},
 {'title': 'Meesaya Murukku',
  'year': 2017,
  'clues': ['Starring Hip Hop Tamizha Adhi, musical coming-of-age comedy.']},
 {'title': 'Hara Hara Mahadevaki', 'year': 2017, 'clues': ['Starring Gautham Karthik, adult comedy.']},
 {'title': 'Kolamavu Kokila', 'year': 2018, 'clues': ['Starring Nayanthara, dark crime comedy.']},
 {'title': 'Kaatrin Mozhi', 'year': 2018, 'clues': ['Starring Jyothika, radio-jockey comedy drama.']},
 {'title': 'Namma Veettu Pillai', 'year': 2019, 'clues': ['Starring Sivakarthikeyan, village family drama.']},
 {'title': 'Thambi', 'year': 2019, 'clues': ['Starring Karthi and Jyothika, family mystery thriller.']},
 {'title': 'Oh My Kadavule',
  'year': 2020,
  'clues': ['Starring Ashok Selvan and Ritika Singh, fantasy romantic comedy.']},
 {'title': 'Mafia: Chapter 1',
  'year': 2020,
  'clues': ['Starring Arun Vijay, stylish police crime thriller.']},
 {'title': 'Nenjam Marappathillai',
  'year': 2021,
  'clues': ['Starring S. J. Suryah, supernatural horror thriller.']},
 {'title': 'Gatta Kusthi',
  'year': 2022,
  'clues': ['Starring Vishnu Vishal and Aishwarya Lekshmi, wrestling comedy.']},
 {'title': 'Ponniyin Selvan: Part I',
  'year': 2022,
  'clues': ['Starring Vikram, Karthi, Jayam Ravi, Aishwarya Rai and Trisha, historical Chola epic.']},
 {'title': 'Ayothi', 'year': 2023, 'clues': ['Starring Sasi Kumar, family and human compassion drama.']},
 {'title': 'Kottukkaali',
  'year': 2024,
  'clues': ['Starring Soori and Anna Ben, rural drama about superstition.']},
 {'title': 'Vaazhai', 'year': 2024, 'clues': ['Starring Ponvel and Rahul, rural coming-of-age drama.']},
 {'title': 'VidaaMuyarchi',
  'year': 2025,
  'clues': ['Starring Ajith Kumar and Trisha, survival thriller set around a missing woman.']},
 {'title': 'Good Bad Ugly',
  'year': 2025,
  'clues': ['Starring Ajith Kumar, gangster action comedy directed by Adhik Ravichandran.']},
 {'title': 'Retro',
  'year': 2025,
  'clues': ['Starring Suriya and Pooja Hegde, romantic gangster action drama.']},
 {'title': 'Dragon',
  'year': 2025,
  'clues': ['Starring Pradeep Ranganathan, college comedy about fraud and relationships.']},
 {'title': 'Tourist Family',
  'year': 2025,
  'clues': ['Starring Sasikumar and Simran, comedy-drama about a Sri Lankan family.']},
 {'title': 'Veera Dheera Sooran: Part 2',
  'year': 2025,
  'clues': ['Starring Vikram and S. J. Suryah, crime action drama.']},
 {'title': 'Bison: Kaalamaadan', 'year': 2025, 'clues': ['Starring Dhruv Vikram, kabaddi sports drama.']},
 {'title': 'Sirai', 'year': 2025, 'clues': ['Starring Vikram Prabhu, prison-transfer road drama.']},
 {'title': 'Dude',
  'year': 2025,
  'clues': ['Starring Pradeep Ranganathan, romantic comedy about childhood friends.']},
 {'title': 'Kaantha', 'year': 2025, 'clues': ['Starring Dulquer Salmaan, period drama set in 1950s Madras.']},
 {'title': 'Parasakthi',
  'year': 2026,
  'clues': ['Starring Sivakarthikeyan, historical drama about the 1965 anti-Hindi agitations.']},
 {'title': 'Vaa Vaathiyaar',
  'year': 2026,
  'clues': ['Starring Karthi, comedy drama about an MGR-loving grandfather and grandson.']},
 {'title': 'Karuppu',
  'year': 2026,
  'clues': ['Starring Suriya and Trisha, action drama involving Karuppu Saamy and justice.']},
 {'title': 'Jana Nayagan',
  'year': 2026,
  'clues': ['Starring Vijay, political action drama directed by H. Vinoth.']},
 {'title': 'Youth', 'year': 2026, 'clues': ['Starring Sai Abhyankkar, romantic musical drama.']},
 {'title': 'Thaai Kizhavi',
  'year': 2026,
  'clues': ['Starring Samuthirakani and others, comedy-drama centered on family relationships.']},
 {'title': 'DC',
  'year': 2026,
  'clues': ['Starring Lokesh Kanagaraj, crime action thriller directed by Arun Matheswaran.']},
 {'title': 'Vishwanath and Sons',
  'year': 2026,
  'clues': ['Starring Suriya and Mamitha Baiju, sports-family drama about a champion shooter.']},
 {'title': 'G.D.N.',
  'year': 2026,
  'clues': ['Starring Madhavan and Priyamani, biographical drama about inventor G. D. Naidu.']},
 {'title': 'Kadhal Kisu Kisu', 'year': 2003, 'clues': ['Starring Bala and Charmy, romantic drama.']},
 {'title': 'Winner', 'year': 2003, 'clues': ['Starring Prashanth, action comedy with family rivalry.']},
 {'title': 'Ji', 'year': 2005, 'clues': ['Starring Ajith Kumar, political action drama.']},
 {'title': 'Chithiram Pesuthadi', 'year': 2006, 'clues': ['Starring Narain and Bhavana, romantic drama.']},
 {'title': 'Em Magan',
  'year': 2006,
  'clues': ['Starring Bharath, family drama about a father-son relationship.']},
 {'title': 'Satham Podathey', 'year': 2007, 'clues': ['Starring Prithviraj, psychological thriller.']},
 {'title': 'Pandhayam', 'year': 2008, 'clues': ['Starring Nithin Sathya, action drama.']},
 {'title': 'Abhiyum Naanum',
  'year': 2008,
  'clues': ['Starring Prakash Raj and Trisha, father-daughter relationship drama.']},
 {'title': 'Peraanmai', 'year': 2009, 'clues': ['Starring Jayam Ravi, forest survival action drama.']},
 {'title': 'Siva Manasula Sakthi', 'year': 2009, 'clues': ['Starring Jiiva and Anuya, romantic comedy.']},
 {'title': 'Thoranai', 'year': 2009, 'clues': ['Starring Vishal, action comedy.']},
 {'title': 'Aayirathil Oruvan',
  'year': 2010,
  'clues': ['Starring Karthi and Andrea, fantasy adventure about Chola history.']},
 {'title': 'Kacheri Arambam', 'year': 2010, 'clues': ['Starring Jiiva, romantic action comedy.']},
 {'title': 'Mappillai', 'year': 2011, 'clues': ['Starring Dhanush, family action comedy.']},
 {'title': 'Osthe', 'year': 2011, 'clues': ['Starring Silambarasan, police action remake.']},
 {'title': 'Muppozhudhum Un Karpanaigal',
  'year': 2012,
  'clues': ['Starring Atharvaa and Amala Paul, romantic psychological thriller.']},
 {'title': 'Dhoni',
  'year': 2012,
  'clues': ['Starring Prakash Raj, family sports drama about a cricket-loving boy.']},
 {'title': 'Sundarapandi', 'year': 2012, 'clues': ['Starring M. Sasikumar, rural romantic drama.']},
 {'title': 'Samar',
  'year': 2013,
  'clues': ['Starring Vishal, action thriller set around a dangerous journey.']},
 {'title': 'Alex Pandian', 'year': 2013, 'clues': ['Starring Karthi, action comedy.']},
 {'title': 'Thanga Meenkal', 'year': 2013, 'clues': ['Starring Ram, emotional father-daughter drama.']},
 {'title': 'Pandiya Naadu', 'year': 2013, 'clues': ['Starring Vishal, revenge action drama.']},
 {'title': 'Naan Sigappu Manithan',
  'year': 2014,
  'clues': ['Starring Vishal, revenge thriller involving narcolepsy.']},
 {'title': 'Yaan', 'year': 2014, 'clues': ['Starring Jiiva, romantic action thriller.']},
 {'title': 'Trisha Illana Nayanthara',
  'year': 2015,
  'clues': ['Starring G. V. Prakash Kumar, youth romantic comedy.']},
 {'title': 'Enakkul Oruvan', 'year': 2015, 'clues': ['Starring Siddharth, psychological thriller.']},
 {'title': 'Eetti', 'year': 2015, 'clues': ['Starring Atharvaa, sports action drama involving javelin.']},
 {'title': 'Kakka Kakka', 'year': 2003, 'clues': ['Starring Suriya and Jyothika, police action romance.']},
 {'title': 'Vedalam',
  'year': 2015,
  'clues': ['Starring Ajith Kumar, action drama about a protective brother.']},
 {'title': 'Vettai',
  'year': 2012,
  'clues': ['Starring Arya and Madhavan, brothers and police action comedy.']},
 {'title': 'Vazhakku Enn 18/9', 'year': 2012, 'clues': ['Starring newcomers, social crime drama.']},
 {'title': 'Kadal Kadandhu Oru Penn', 'year': 2017, 'clues': ['Starring Gautham Karthik, romantic drama.']},
 {'title': 'Richie', 'year': 2017, 'clues': ['Starring Nivin Pauly, coastal gangster drama.']},
 {'title': 'Spyder', 'year': 2017, 'clues': ['Starring Mahesh Babu, Tamil-Telugu action thriller.']},
 {'title': 'Nenjil Thunivirundhal', 'year': 2017, 'clues': ['Starring Sundeep Kishan, action thriller.']},
 {'title': 'Seethakaathi',
  'year': 2018,
  'clues': ['Starring Vijay Sethupathi, drama about an uncompromising actor.']},
 {'title': 'Silukkuvarpatti Singam', 'year': 2018, 'clues': ['Starring Vishnu Vishal, police comedy.']},
 {'title': 'Monster', 'year': 2019, 'clues': ['Starring S. J. Suryah, comedy involving a rat.']},
 {'title': 'LKG', 'year': 2019, 'clues': ['Starring R. J. Balaji, political satire.']},
 {'title': 'Mehandi Circus', 'year': 2019, 'clues': ['Starring Madhampatty Rangaraj, romantic drama.']},
 {'title': 'Kalathil Santhippom',
  'year': 2021,
  'clues': ['Starring Jiiva and Arulnithi, friendship and sports drama.']},
 {'title': 'Maara',
  'year': 2021,
  'clues': ['Starring Madhavan and Shraddha Srinath, romantic mystery drama.']},
 {'title': 'Kasada Thabara',
  'year': 2021,
  'clues': ['Starring Harish Kalyan and others, six interconnected stories.']},
 {'title': 'Cobra', 'year': 2022, 'clues': ['Starring Vikram, mathematical crime thriller.']},
 {'title': 'Nenjukku Needhi',
  'year': 2022,
  'clues': ['Starring Udhayanidhi Stalin, social political drama.']},
 {'title': 'Iravin Nizhal',
  'year': 2022,
  'clues': ['Starring Radhakrishnan Parthiban, experimental single-shot thriller.']},
 {'title': 'Sardar', 'year': 2022, 'clues': ['Starring Karthi in dual roles, spy action thriller.']},
 {'title': 'Diary', 'year': 2022, 'clues': ['Starring Arulnithi, mystery thriller involving a bus route.']},
 {'title': 'Ponniyin Selvan: Part Two',
  'year': 2023,
  'clues': ['Starring Vikram, Karthi, Jayam Ravi, Aishwarya Rai and Trisha, Chola historical epic.']},
 {'title': 'Kannur Squad',
  'year': 2023,
  'clues': ['Starring Mammootty, police investigation thriller in Tamil-Malayalam context.']},
 {'title': 'Takkar', 'year': 2023, 'clues': ['Starring Siddharth, romantic action drama.']},
 {'title': 'Joe', 'year': 2023, 'clues': ['Starring Rio Raj, romantic coming-of-age drama.']},
 {'title': 'Lover', 'year': 2024, 'clues': ['Starring Manikandan, modern relationship drama.']},
 {'title': 'Blue Star',
  'year': 2024,
  'clues': ['Starring Ashok Selvan and Shanthanu, cricket and romance drama.']},
 {'title': 'Siren',
  'year': 2024,
  'clues': ['Starring Jayam Ravi, action thriller about a prisoner and ambulance driver.']},
 {'title': 'Demonte Colony 2', 'year': 2024, 'clues': ['Starring Arulnithi, supernatural horror sequel.']},
 {'title': 'The Greatest of All Time',
  'year': 2024,
  'clues': ['Starring Vijay, spy action thriller with dual roles.']},
 {'title': 'Vettaiyan',
  'year': 2024,
  'clues': ['Starring Rajinikanth, police action drama about justice and education.']},
 {'title': 'Indian 2',
  'year': 2024,
  'clues': ['Starring Kamal Haasan, vigilante action drama about corruption.']},
 {'title': 'Rathnam', 'year': 2024, 'clues': ['Starring Vishal, action drama protecting a young woman.']},
 {'title': 'Brother', 'year': 2024, 'clues': ['Starring Jayam Ravi, family comedy drama.']},
 {'title': 'Bloody Beggar',
  'year': 2024,
  'clues': ["Starring Kavin, dark comedy about a beggar's unexpected adventure."]},
 {'title': 'Thug Life',
  'year': 2025,
  'clues': ['Starring Kamal Haasan and Silambarasan, gangster action drama.']},
 {'title': 'Coolie',
  'year': 2025,
  'clues': ['Starring Rajinikanth, action thriller about a smuggling syndicate.']},
 {'title': 'Aghathiyaa', 'year': 2025, 'clues': ['Starring Jiiva, fantasy horror thriller.']},
 {'title': 'Bottle Radha', 'year': 2025, 'clues': ['Starring Guru Somasundaram, dark comedy drama.']},
 {'title': 'Mura', 'year': 2025, 'clues': ['Starring Hridhu Haroon, crime drama with Tamil dialogue.']},
 {'title': 'Maaman', 'year': 2025, 'clues': ['Starring Soori, family comedy drama.']},
 {'title': 'Kudumbasthan', 'year': 2025, 'clues': ['Starring K. Manikandan, family comedy.']},
 {'title': 'Kombu Vacha Singamda',
  'year': 2022,
  'clues': ['Starring M. Sasikumar, rural political action drama.']},
 {'title': 'Koogle Kuttappa',
  'year': 2022,
  'clues': ['Starring K. S. Ravikumar, comedy about a robot companion.']},
 {'title': 'FIR',
  'year': 2022,
  'clues': ['Starring Vishnu Vishal, crime thriller about a terrorism accusation.']},
 {'title': 'Buffoon', 'year': 2022, 'clues': ['Starring Vaibhav, political crime drama.']},
 {'title': 'Kuthiraivaal', 'year': 2022, 'clues': ['Starring Kalaiyarasan, surreal psychological drama.']},
 {'title': 'Hey Sinamika',
  'year': 2022,
  'clues': ['Starring Dulquer Salmaan and Aditi Rao Hydari, romantic drama.']},
 {'title': 'O2', 'year': 2022, 'clues': ['Starring Nayanthara, survival thriller involving a bus.']},
 {'title': 'Anbarivu',
  'year': 2022,
  'clues': ['Starring Hiphop Tamizha Adhi, family drama with twin brothers.']},
 {'title': 'Clap', 'year': 2022, 'clues': ['Starring Aadhi, sports drama about an athlete.']},
 {'title': 'The Great Indian Kitchen',
  'year': 2023,
  'clues': ['Starring Aishwarya Rajesh, social family drama.']},
 {'title': 'Thunivu', 'year': 2023, 'clues': ['Starring Ajith Kumar, bank heist action thriller.']},
 {'title': 'Raavana Kottam', 'year': 2023, 'clues': ['Starring Shanthnu, rural political drama.']},
 {'title': 'Bommai', 'year': 2023, 'clues': ['Starring S. J. Suryah, romantic psychological thriller.']},
 {'title': 'Adiyae',
  'year': 2023,
  'clues': ['Starring G. V. Prakash Kumar, science-fiction romantic comedy.']},
 {'title': 'Regina', 'year': 2023, 'clues': ['Starring Sunainaa, crime thriller.']},
 {'title': 'Theera Kaadhal',
  'year': 2023,
  'clues': ['Starring Jai and Aishwarya Rajesh, relationship drama.']},
 {'title': 'Iraivan', 'year': 2023, 'clues': ['Starring Jayam Ravi, serial-killer thriller.']},
 {'title': 'Sorgavaasal', 'year': 2024, 'clues': ['Starring RJ Balaji, prison crime drama.']},
 {'title': 'J. Baby', 'year': 2024, 'clues': ['Starring Urvashi and Dinesh, emotional family drama.']},
 {'title': 'Rebel', 'year': 2024, 'clues': ['Starring Mamitha Baiju and Adhi, political campus drama.']},
 {'title': 'Joshua: Imai Pol Kaakha', 'year': 2024, 'clues': ['Starring Varun, action thriller.']},
 {'title': 'Singapore Saloon', 'year': 2024, 'clues': ['Starring R. J. Balaji, barber comedy drama.']},
 {'title': 'Mission: Chapter 1',
  'year': 2024,
  'clues': ['Starring Arun Vijay, prison escape action thriller.']},
 {'title': 'Black',
  'year': 2024,
  'clues': ['Starring Jiiva and Priya Bhavani Shankar, science-fiction thriller.']},
 {'title': 'Eleven', 'year': 2025, 'clues': ['Starring Naveen Chandra, crime thriller.']},
 {'title': 'Phoenix', 'year': 2025, 'clues': ['Starring Surya Sethupathi, action drama.']},
 {'title': 'Marma Yogi', 'year': 2025, 'clues': ['Starring Tamil ensemble, mystery drama.']},
 {'title': '3BHK', 'year': 2025, 'clues': ['Starring Siddharth, family drama about buying a home.']},
 {'title': 'Kuberaa', 'year': 2025, 'clues': ['Starring Dhanush, Nagarjuna and Rashmika, crime drama.']},
 {'title': 'With Love', 'year': 2026, 'clues': ['Starring Kavin, romantic drama.']},
 {'title': 'Kovil', 'year': 2004, 'clues': ['Starring Arjun and Sonia Agarwal, village romance drama.']},
 {'title': 'February 14', 'year': 2005, 'clues': ['Starring Bharath and Renuka Menon, romantic drama.']},
 {'title': 'Aathi', 'year': 2006, 'clues': ['Starring Vijay, action drama about revenge.']},
 {'title': 'Aadhavan', 'year': 2009, 'clues': ['Starring Suriya, action comedy about a hitman.']},
 {'title': 'Naduvula Konjam Pakkatha Kaanom',
  'year': 2012,
  'clues': ['Starring Vijay Sethupathi, comedy about memory loss.']},
 {'title': 'Joker', 'year': 2016, 'clues': ['Starring Guru Somasundaram, political satire.']},
 {'title': 'Kolaigaran',
  'year': 2019,
  'clues': ['Starring Vijay Antony and Arjun, murder mystery thriller.']},
 {'title': 'Perazhagan', 'year': 2004, 'clues': ['Starring Suriya in dual roles, romantic drama.']},
 {'title': 'Veyil', 'year': 2006, 'clues': ['Starring Pasupathy and Bharath, emotional rural drama.']},
 {'title': 'Kattradhu Thamizh', 'year': 2007, 'clues': ['Starring Jiiva, intense social drama.']},
 {'title': 'Saroja',
  'year': 2008,
  'clues': ['Starring Shiva, Vaibhav and Premji, road-trip comedy thriller.']},
 {'title': 'Easan', 'year': 2010, 'clues': ['Starring Samuthirakani and Vaibhav, revenge drama.']},
 {'title': 'Pichaikkaran', 'year': 2016, 'clues': ['Starring Vijay Antony, emotional action drama.']},
 {'title': 'Kazhugu',
  'year': 2012,
  'clues': ['Starring Krishna and Bindu Madhavi, romantic thriller around a risky job.']},
 {'title': 'Aaranya Kaandam',
  'year': 2011,
  'clues': ['Starring Jackie Shroff and Ravi Krishna, neo-noir gangster drama.']},
 {'title': 'Sillunu Oru Kadhal',
  'year': 2006,
  'clues': ['Starring Suriya and Jyothika, romantic family drama.']},
 {'title': 'Aruvi',
  'year': 2016,
  'clues': ["Starring Aditi Balan, social drama about a young woman's struggle against society."]},
 {'title': 'Kavan', 'year': 2017, 'clues': ['Starring Vijay Sethupathi, media and political thriller.']},
 {'title': 'Airaa',
  'year': 2019,
  'clues': ['Starring Nayanthara in dual roles, supernatural horror thriller.']},
 {'title': 'Gatta Kusthi 2',
  'year': 2026,
  'clues': ['Starring Vishnu Vishal and Aishwarya Lekshmi, wrestling-family sports drama.']},
 {'title': 'Nooru Saami',
  'year': 2026,
  'clues': ['Starring Vijay Antony, emotional family biographical drama.']},
 {'title': 'Magudam',
  'year': 2026,
  'clues': ['Starring Vishal, revenge action drama set against a coastal backdrop.']},
 {'title': 'Blast', 'year': 2026, 'clues': ['Starring Arjun Sarja, action thriller.']},
 {'title': 'LIK: Love Insurance Kompany',
  'year': 2026,
  'clues': ['Starring Pradeep Ranganathan and Krithi Shetty, futuristic romantic comedy.']},
 {'title': 'Kara', 'year': 2026, 'clues': ['Starring Dhanush, action thriller set around the Gulf War era.']},
 {'title': 'Jockey',
  'year': 2026,
  'clues': ['Starring Yuvan Krishna, rural action drama around traditional goat fighting.']},
 {'title': 'Hi',
  'year': 2026,
  'clues': ['Starring Kaavya Arivumani, romantic drama about finding love through an unconventional '
            'marriage.']}]
